---
stages:
  - syntax
  - unit

default:
  cache:
    paths:
      - vendor/bundle

  before_script: &before_script
    - pdk --version
    - rm Gemfile.lock || true
  
validate lint check rubocop-Ruby 2.7.7-Puppet ~> 7:
  stage: syntax
  image: 
    name: puppet/pdk:3.0.1.3
    entrypoint:
      - ""
  script:
    - pdk validate --puppet-version 7
  variables:
    PUPPET_GEM_VERSION: '~> 7'

parallel_spec-Ruby 2.7.7-Puppet ~> 7:
  stage: unit
  image: 
    name: puppet/pdk:3.0.1.3
    entrypoint:
      - ""
  script:
    - pdk test unit --puppet-version 7
  variables:
    PUPPET_GEM_VERSION: '~> 7'

validate lint check rubocop-Ruby 3.2-Puppet ~> 8:
  stage: syntax
  image: 
    name: puppet/pdk:3.0.1.3
    entrypoint:
      - ""
  script:
    - pdk validate --puppet-version 8
  variables:
    PUPPET_GEM_VERSION: '~> 8'

parallel_spec-Ruby 3.2-Puppet ~> 8:
  stage: unit
  image: 
    name: puppet/pdk:3.0.1.3
    entrypoint:
      - ""
  script:
    - pdk test unit --puppet-version 8
  variables:
    PUPPET_GEM_VERSION: '~> 8'